// This file exists so that changing the dev env dependencies does not recompile all the modules (which takes around a minute and is annoying to wait for).

apply from: "gradle/scripts/dependencies.gradle"

def enabledDependencies = [
  // Dev Env stuff
  "jei": true,
  "top": true,
  "waila": false,
  "aa": false,
  "rftools": false,
  "omniwand": false,
  "chisel": false,
  "indy": false,
  "profiler": false,
  "bloodmagic": true,
  // Modules
  "endergy": true,
  "zoo": false,
  // Integration
  "thaumcraft": false,
  "opencomputers": false,
  "forestry": false,
  "rs": false,
  "mekanism": false,
  "ae2": false,
  "tconstruct": false,
  "cofh_core": false,
  "ftblib": false,
  "ctm": false,
  "project_intelligence": false,
]

def shouldUse(deps, value) {
  switch(value) {
    case Boolean:
      return value
    case String:
      if (!deps.containsKey(value)) {
        throw new RuntimeException("Unknown mod switch: " + value)
      }
      return deps[value]
    case Map:
      if (value.containsKey("and") && value.containsKey("or")) {
        throw new RuntimeException("Value ${value} contains both an AND and an OR")
      } else if (value.containsKey("and")) {
        return !value["and"].any { !shouldUse(deps, it) }
      } else if (value.containsKey("or")) {
        return value["or"].any { shouldUse(deps, it) }
      } else {
        throw new RuntimeException("Invalid map ${value}")
      }
    case _:
      throw new RuntimeException("Invalid expression ${value}")
  }
}

def runtime_only_dependencies = [
    'curse.maven:hwyla-253449:2568751': "waila",
    'curse.maven:actually-additions-228404:3117927': "aa",
    'curse.maven:rftools-224641:2861573': "rftools",
    'curse.maven:mcjtylib-233105:2745846': "rftools",
    'curse.maven:omniwand-923677:7476868': "omniwand",
    'curse.maven:chisel-235279:2915375': "chisel",
    'curse.maven:ctm-267602:2915363': "chisel",
    'curse.maven:integrated-crafting-287357:3010631': "indy",
    'curse.maven:integrated-tunnels-251389:3159511': "indy",
    'curse.maven:integrated-dynamics-236307:3159505': "indy",
    'curse.maven:common-capabilities-247007:3053017': "indy",
    'curse.maven:cyclops-core-232758:3159497': "indy",
    // 'curse.maven:flare-692142:7857037': "profiler",
    // 'curse.maven:configanytime-870276:5212709': "profiler",
    // 'curse.maven:spark-unforged-900927:6751437': "profiler",
    // 'curse.maven:mixin-booter-419286:7049694': "profiler",
    'curse.maven:spark-361579:3542217': "profiler",
    'curse.maven:blood-magic-224791:2822288': "bloodmagic",
    'curse.maven:guide-api-228832:2645992': "bloodmagic",
]

dependencies {
  // Include StripLatestForgeRequirements by default for the dev env, saves everyone a hassle
  runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
  // Include OSXNarratorBlocker by default for the dev env, for M1+ Macs
  runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'

  runtime_only_dependencies.entrySet().forEach {
    if (shouldUse(enabledDependencies, it.value)) {
      runtimeOnly it.key
    }
  } 
  compile_dependencies.entrySet().forEach {
    if (shouldUse(enabledDependencies, it.value)) {
      runtimeOnly it.key
    }
  } 

  implementation project(":endercore")  
  loaded_modules.entrySet().forEach {
    if (shouldUse(enabledDependencies, it.value)) {
      implementation (project(":enderio-${it.key}")) {
        transitive = false
      }
    }
  }

}

