mod_id = endercore
mod_name = Ender Core
mod_description = Library mod used by EnderIO, EnderZoo, and others
mod_version = 1.12.2-0.5.83
mod_authors = ["tterrag", "CrazyPants", "HenryLoenwind"]
tag_class_name = com.enderio.core.Tags
mod_dependencies =

is_coremod = true
coremod_plugin_class_name = com.enderio.core.common.transform.EnderCorePlugin
